// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXdyKKSbfjjwwtkRPXhffjWDewi3Hyszw',
    appId: '1:920202807130:web:3b4febee700d2ff1095563',
    messagingSenderId: '920202807130',
    projectId: 'authflutter-e424a',
    authDomain: 'authflutter-e424a.firebaseapp.com',
    storageBucket: 'authflutter-e424a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRE2w1X3LWFQXERGewAESXKOKiGjXslMQ',
    appId: '1:920202807130:android:10d8526fe4e03229095563',
    messagingSenderId: '920202807130',
    projectId: 'authflutter-e424a',
    storageBucket: 'authflutter-e424a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBOZKG5YICuejPZdEHn46TfqMXtLDAW_4',
    appId: '1:920202807130:ios:0606ee06a0c00a50095563',
    messagingSenderId: '920202807130',
    projectId: 'authflutter-e424a',
    storageBucket: 'authflutter-e424a.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBOZKG5YICuejPZdEHn46TfqMXtLDAW_4',
    appId: '1:920202807130:ios:0606ee06a0c00a50095563',
    messagingSenderId: '920202807130',
    projectId: 'authflutter-e424a',
    storageBucket: 'authflutter-e424a.appspot.com',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXdyKKSbfjjwwtkRPXhffjWDewi3Hyszw',
    appId: '1:920202807130:web:de475d0b30700dff095563',
    messagingSenderId: '920202807130',
    projectId: 'authflutter-e424a',
    authDomain: 'authflutter-e424a.firebaseapp.com',
    storageBucket: 'authflutter-e424a.appspot.com',
  );
}
